const PDFDocument = require("pdfkit");
const QRCode      = require("qrcode");

async function generateReceiptPDF(res, { payment, fromUser, toUser, expenses }) {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=receipt-${payment._id}.pdf`);
  doc.pipe(res);

  // Header
  doc.rect(0, 0, doc.page.width, 80).fill("#2a78d6");
  doc.fillColor("#ffffff").fontSize(22).font("Helvetica-Bold").text("SplitEase", 50, 25);
  doc.fontSize(11).font("Helvetica").text("Payment Receipt", 50, 52);
  doc.fillColor("#0b0b0b");

  // Receipt ID & Date
  doc.moveDown(3);
  doc.fontSize(11).fillColor("#898781").text(`Receipt ID: ${payment._id}`, { align: "right" });
  doc.text(`Date: ${new Date(payment.createdAt).toLocaleDateString("en-IN", { dateStyle: "long" })}`, { align: "right" });

  // Amount
  doc.moveDown(1);
  doc.fontSize(36).font("Helvetica-Bold").fillColor("#2a78d6")
     .text(`₹${payment.amount.toLocaleString()}`, { align: "center" });
  doc.fontSize(13).font("Helvetica").fillColor("#52514e")
     .text("Total Settled", { align: "center" });

  // Divider
  doc.moveDown(1).moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#e8e7e4").stroke();

  // From / To
  doc.moveDown(1);
  const col = (label, value, x) => {
    doc.fontSize(10).fillColor("#898781").font("Helvetica").text(label, x, doc.y);
    doc.fontSize(13).fillColor("#0b0b0b").font("Helvetica-Bold").text(value, x, doc.y + 14);
  };
  const y = doc.y;
  col("From", fromUser.name, 50);
  doc.y = y;
  col("To", toUser.name, 300);

  doc.moveDown(3);
  doc.fontSize(11).fillColor("#898781").text(`Payment Mode: ${payment.paymentMode}`);
  if (payment.transactionNote)
    doc.text(`Note: ${payment.transactionNote}`);

  // Expense breakdown table
  if (expenses && expenses.length) {
    doc.moveDown(1).moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#e8e7e4").stroke().moveDown(0.5);
    doc.fontSize(12).font("Helvetica-Bold").fillColor("#0b0b0b").text("Expense Breakdown");
    doc.moveDown(0.5);

    // Table header
    doc.rect(50, doc.y, 495, 22).fill("#f1f0ec");
    doc.fontSize(10).font("Helvetica-Bold").fillColor("#52514e");
    doc.text("Description", 55, doc.y + 6);
    doc.text("Total", 360, doc.y - 16, { width: 80, align: "right" });
    doc.text("Your Share", 440, doc.y - 16, { width: 100, align: "right" });
    doc.moveDown(1.2);

    expenses.forEach((e, i) => {
      const rowY = doc.y;
      if (i % 2 === 0) doc.rect(50, rowY, 495, 20).fill("#fafafa");
      doc.fontSize(10).font("Helvetica").fillColor("#0b0b0b");
      doc.text(e.description, 55, rowY + 5, { width: 290 });
      doc.text(`₹${e.amount.toLocaleString()}`, 355, rowY + 5, { width: 80, align: "right" });
      doc.text(`₹${Math.round(e.amount / e.splitBetween.length).toLocaleString()}`, 435, rowY + 5, { width: 105, align: "right" });
      doc.moveDown(0.8);
    });
  }

  // QR Code verification
  doc.moveDown(1).moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#e8e7e4").stroke().moveDown(1);
  const qrData = `${process.env.APP_URL}/verify/${payment._id}`;
  const qrBuffer = await QRCode.toBuffer(qrData, { width: 80 });
  doc.image(qrBuffer, 50, doc.y, { width: 80 });
  doc.fontSize(9).fillColor("#898781")
     .text("Scan to verify this receipt", 145, doc.y - 40)
     .text(qrData, 145, doc.y - 25);

  // Footer
  const footerY = doc.page.height - 50;
  doc.moveTo(50, footerY - 10).lineTo(545, footerY - 10).strokeColor("#e8e7e4").stroke();
  doc.fontSize(9).fillColor("#898781")
     .text("Generated by SplitEase · This is a digitally verified receipt", 50, footerY, { align: "center" });

  doc.end();
}

module.exports = { generateReceiptPDF };
